# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Analytics from Yandex cozgis username personal cell phone as backup phone number

# Site
title: City of Zanesville | Maps & Apps
subtitle:
description: Online web and map applications for the City of Zanesville. This site is managed by the City of Zanesville Department of Public Service, Division of Engineering.
keywords: maps zanesville city muskingum engineer
author: City of Zanesville | Division of Engineering
language: en
timezone: America/New_York

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: "http://127.0.0.1:4000"
root: ""
permalink: /:title/
permalink_defaults:

#Server settings
server:
  port: 4000
  log: false
  ip: 127.0.0.1
  compress: true
  header: true
  serveStatic:
    extensions:
    - html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: coz-app-archive
category_dir: /
code_dir:
i18n_dir: :lang
include: 
  - '_redirects'
  - '_headers'
skip_render:
  - '**/*.js'
  - '**/*.json'
  - '**/*.geojson'
  - '**/*.mvt'
  - 'docs/**/*'
  - '_redirects'
  - '_headers'
  - 'admin/**/*.*'
  - 'preview/index.html'

exclude: "scripts"

# Writing
new_post_name: :title.html # File name of new posts
default_layout: map
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)

index_generator:
  path: ''
  per_page: 20
  order_by: date

# Category & Tag
#default_category: maps
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MM-DD-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

##############
# Extensions #
##############

## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: spectre

#hexo-pages - modified in source

#Category Generator
category_generator:
  per_page: 10

#Archive Generator
archive_generator:
  per_page: 10
  yearly: false
  monthly: false
  daily: false
  order_by: -date

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# Netlify: 
#deploy:
 # type: netlify
  #token: 9c5be66a6daa3a0d4ff057344397276a6ee52b100122ce4ed5177cd979b1ac7c
  #site_id: 52f0542b-4fea-4774-88b8-45c72ac6a902
  # zip: true  #deploy with zip file. 

#hexo-cdnify modified - could not get this to work properly - revisit sometime, using gulp-replace instead
cdn:
  enable: false
  base: https://gis.coz.org
  local: http://127.0.0.1:4000
  #tags:
   # 'link[property="og:image"]': content
    #'meta[property="og:image"]': content
    #'link[property="og:url"]'  : content

#hexo-pages
pages:
  path: "source/pages"

#https://github.com/hexojs/hexo-asset-pipeline 
asset_pipeline:
  revisioning:
    enable: false
  clean_css:
    enable: false
  uglify_js:
    enable: false
  imagemin:
    enable: false
  html_minifier:
    enable: true

all_minifier: true
#If you need futher control of this plugin, please refer the options below.

js_concator:
  enable: false
  bundle_path:
  front: false
  silent: false

js_minifier:
  enable: true
  mangle: false
  silent: false
  output:
  compress:
  exclude: 
    - '*.min.js'
  include:

html_minifier:
  enable: true
  ignore_error: false
  silent: true

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 4
  pngquant: false
  progressive: false
  silent: true

#snapshot url = https://cozgis.netlify.com/public/sewer-viewer/#14.93/39.94042/-82.0118
# current 768 x 434

# Security - hexo-blog-encrypt - did not work right

auto_dir_categorize:
  enable: true  # options:true, false; default is true
  force: false # options:true, false; default is false

# mapbox dataset edit token
# sk.eyJ1IjoiY296Z2lzIiwiYSI6ImNqczM2eWQxYjF3emw0NG85bGN0cjJmOWgifQ.dHmpgehC8hN2-t4svOJnng

#hexo-renderer-webpack
#webpack:
 # entry: 'source/assets/js/build/coz-scripts-parcel.js'
  #output: 'source/assets/js/build/coz-scripts-parcel.webpack.js'

browsersync:
  port: 3002

html_prettify:
    enable: true
    exclude:
        - "*/**/test"
    options:
        indent_size: 2
        indent_char: " "
        max_preserve_newlines: "-1"
        preserve_newlines: false
        keep_array_indentation: true
        break_chained_methods: false
        indent_scripts: normal
        brace_style: expand
        space_before_conditional: true
        unescape_strings: false
        jslint_happy: true
        end_with_newline: true
        wrap_line_length: "0"
        indent_inner_html: false
        comma_first: false
        e4x: false
        indent_empty_lines: false

search:
  path: search.json
  field: all
  content: false